# Generated by Django 4.1.3 on 2022-12-02 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('deployment_state', models.TextField(blank=True, max_length=50, null=True)),
                ('incident_state', models.TextField(blank=True, max_length=50, null=True)),
                ('vendor', models.TextField(blank=True, max_length=50, null=True)),
                ('model', models.TextField(blank=True, max_length=50, null=True)),
                ('type', models.TextField(blank=True, max_length=50, null=True)),
                ('property', models.TextField(blank=True, max_length=50, null=True)),
                ('site', models.TextField(blank=True, max_length=50, null=True)),
                ('warranty', models.DateField(blank=True, null=True)),
                ('install', models.DateField(blank=True, null=True)),
                ('asignment', models.TextField(blank=True, max_length=50, null=True)),
                ('cpu', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
