# Generated by Django 4.1.3 on 2022-11-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('deployment_state', models.TextField(max_length=50, unique=True)),
                ('incident_state', models.TextField(max_length=50)),
                ('vendor', models.TextField(max_length=50)),
                ('model', models.TextField(max_length=50)),
                ('type', models.TextField(max_length=50)),
                ('property', models.TextField(max_length=50)),
                ('site', models.TextField(max_length=50)),
                ('warranty', models.DateField(max_length=50)),
                ('install', models.DateField(max_length=50)),
                ('asignment', models.TextField(max_length=50)),
                ('cpu', models.TextField(max_length=50)),
            ],
        ),
    ]
