# Generated by Django 4.1.3 on 2022-11-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Computers',
            new_name='Computer',
        ),
    ]
