# Generated by Django 4.1.4 on 2022-12-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0002_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
