# Generated by Django 4.1.4 on 2022-12-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0003_alter_laptop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='laptop',
            unique_together={('name', 'price', 'processor', 'operating_system', 'graphics', 'memory', 'storage', 'display')},
        ),
    ]
