# Generated by Django 4.1.3 on 2022-11-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0003_alter_computer_asignment_alter_computer_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='install',
            field=models.DateField(blank=True, default='<jamming-date>', null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='warranty',
            field=models.DateField(blank=True, default='<jamming-date>', null=True),
        ),
    ]
