# Generated by Django 4.1.4 on 2022-12-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0004_alter_laptop_name_alter_laptop_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='carbon_footprint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
