# Generated by Django 4.1.3 on 2022-12-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0005_laptop_carbon_footprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='average_lifetime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='energy_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
