# Generated by Django 4.1.3 on 2022-11-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0006_alter_computer_install_alter_computer_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='install',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='warranty',
            field=models.DateField(blank=True, null=True),
        ),
    ]
