# Generated by Django 4.1.4 on 2022-12-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0006_laptop_average_lifetime_laptop_energy_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
