# Generated by Django 4.1.4 on 2023-01-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0007_laptop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='energy_consumption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
